#!/usr/bin/python

# MIT License
#
# Copyright (c) 2021 Rik Baehnemann, ASL, ETH Zurich, Switzerland
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sellpython
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from fm_radar_driver.detect_circles import*

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Extract start and stop of circular trajectories in standard system test.')
    parser.add_argument('input_bag', nargs=1, help='The bag containing the onboard sensor data.')
    parser.add_argument('out_file', nargs=1, help='The output file to store the segment times.')
    parser.add_argument('trajectory_topic', nargs=1, help='The trajectory command topic.')

    args = parser.parse_args()

    print("Input bag: %s" %(args.input_bag[0]))
    print("Out file: %s" %(args.out_file[0]))
    print("Trajectory topic: %s" %(args.trajectory_topic[0]))

    detect_circles(args.input_bag[0], args.out_file[0], args.trajectory_topic[0])
